version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=TZ=America/Sao_paulo
    volumes:
    - /home/butt/Docker/nextcloud/config:/config
    - /home/butt/Docker/nextcloud/data:/data
    ports:
    - 443:443

  