version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer-ce
    privileged: true
    labels:
    - 'portainer.localhost' 
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Sao_paulo
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/butt/Docker/portainer-ce/conf:/data
    ports:
    - 9000:9000
    restart: always
    networks:
      - frontend

  duckdns:
    image: ghcr.io/linuxserver/duckdns	
    container_name: duckdns	
    environment:	
    - PUID=1000	
    - PGID=100	
    - TZ=America/Sao_Paulo	
    - SUBDOMAINS=userverhome-c001
    - TOKEN=ad68a933-0ece-445c-ae15-aecfb96c9c5c # fabricio.butt@gmail.com
    - LOG_FILE=false
    - UPDATE_IP=ipv4 # ipv6 both lan
    volumes:
      - /home/butt/Docker/duckdns/config/duck.sh:/app/duck.sh
      - /home/butt/Docker/duckdns/config/hostname:/app/hostname
    restart: unless-stopped	 
    networks:
      - frontend

  tunnel-bridge:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_home_bserver
    command: tunnel --no-autoupdate run --token eyJhIjoiMjJiZTQwZTM5YzlhMzg4Njg5ZjQ4ZjI4YTc2ZDlkMGYiLCJ0IjoiNzQ5MjQ0YmItYzg2NC00YzQ5LThlMzctOTA3MjU1Y2NmMDc3IiwicyI6Ik1EQTNabVJpWmpRdFpHVmpaaTAwTW1FM0xXRXpNRGd0Tm1ReE5tSTNOREF5TVRBMiJ9
    restart: always
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    external: true
    #attachable: true