version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - traefik.http.routers.sonarr.rule=Host(`series.server`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.port=80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/butt/Docker/sonarr/config:/config
      - /media/butt/Downloads/ButtFlix/tvseries:/tv #optional
      - /media/butt/Downloads/ButtFlix/downloads:/downloads #o mesmo do qBittorrent
    #ports:
      #- 4001:8989
    restart: unless-stopped

#services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    labels:
      - traefik.http.routers.jackett.rule=Host(`jackett.server`)
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - traefik.port=80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_paulo
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/butt/Docker/jackett/config:/config
      - /home/butt/Docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
networks:
  default:
    external:
      name: dns-net
