version: '3.8'
services:
  portainer-ce:
    image: portainer/portainer-ce
    container_name: portainer
    privileged: true
    labels:
    - 'portainer.localhost' 
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Sao_paulo
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    #- /mnt/f/butt/docker/portainer-win/conf:/data
    - /home/docker/portainer-ce/conf:/data
    ports:
    - 9000:9000
    restart: always
    networks:
      - frontend

  duckdns:
    image: ghcr.io/linuxserver/duckdns	
    container_name: duckdns	
    environment:	
      - PUID=1000	
      - PGID=1000	
      - TZ=America/Sao_Paulo	
      - SUBDOMAINS=dei-djgl2l3-local #udesktop-lan
      - TOKEN=ad68a933-0ece-445c-ae15-aecfb96c9c5c # fabricio.butt@gmail.com
      #- TOKEN=a24ba2c9-aa4d-4c00-b4de-db3baa414f94 # fabriciogmabillot@gmail.com
      - LOG_FILE=false
      #- UPDATE_IP=ipv4 # ipv6 both lan
    #volumes:
      #- /mnt/f/docker/duckdns/config/duck.sh:/app/duck.sh
      #- /home/docker/duckdns/config/duck.sh:/app/duck.sh
      #- /home/docker/duckdns/config/hostname:/app/hostname
    restart: unless-stopped	 
    networks:
      - frontend

  tunnel-bridge:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_home_bserver
  #uDesktop wDesktop
    command: tunnel --no-autoupdate run --token eyJhIjoiMjJiZTQwZTM5YzlhMzg4Njg5ZjQ4ZjI4YTc2ZDlkMGYiLCJ0IjoiNzQ5MjQ0YmItYzg2NC00YzQ5LThlMzctOTA3MjU1Y2NmMDc3IiwicyI6Ik1EQTNabVJpWmpRdFpHVmpaaTAwTW1FM0xXRXpNRGd0Tm1ReE5tSTNOREF5TVRBMiJ9
  #pcie
  # command: tunnel --no-autoupdate run --token eyJhIjoiMjJiZTQwZTM5YzlhMzg4Njg5ZjQ4ZjI4YTc2ZDlkMGYiLCJ0IjoiYjkzZmM5MDgtOTAyYy00ZDUzLWJjODQtYzFkNTljNjkzYzQ5IiwicyI6IlpUazRZVEkwWTJJdE9HSXpaQzAwWXpOaExXRXlOVEV0WkdWaFpqZGxPV1kwWmpFeCJ9
    restart: always
    networks:
      - frontend

networks:
  frontend:
    name: frontend
    #external: true
    attachable: true
#run --rm -v /home/docker/portainer-ce/conf:/data portainer/helper-reset-password