version: '3'
networks:
  default:
    name: tunnel_net_media
services:
  tunnel-buttflix:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_net_media
    command: tunnel --no-autoupdate run --token eyJhIjoiMjJiZTQwZTM5YzlhMzg4Njg5ZjQ4ZjI4YTc2ZDlkMGYiLCJ0IjoiN2NlOWY0ZmItOGU1Yy00MzQzLTgyNWMtYTM5ZWZlNmRhN2ZlIiwicyI6IllXWmlOV1poWVRrdFlXVmpZaTAwWm1GakxUazNZek10WlRZelpERmxaRGczWWpBMCJ9
    restart: unless-stopped

  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    labels:
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.localhost`)
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8000
      - traefik.http.routers.qbittorrent.tls=true
      #- traefik.http.routers.emby.entrypoints=entryhttps
      #- traefik.http.routers.qbittorrent.certresolver=certresolver # em traefik.yml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_paulo
      - WEBUI_PORT=8000
    volumes:
      - /home/butt/Docker/qBittorrent/config:/config
      - /media/butt/backup/Videos/MovieFlix/downloads/:/downloads
    ports:
      #- 8002:6881
      #- 8003:6881/udp
      - 8000:8000
    restart: unless-stopped
#services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    labels:
      - traefik.http.routers.jackett.rule=Host(`jackett.localhost`)
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - traefik.http.routers.jackett.tls=true
      #- traefik.http.routers.emby.entrypoints=entryhttps
      #- traefik.http.routers.jackett.certresolver=certresolver# em traefik.yml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_paulo
      - AUTO_UPDATE=true #optional     
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/butt/Docker/jackett/config:/config
      - /home/butt/Docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
#services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    labels:
      - traefik.http.routers.sonarr.rule=Host(`sonarr.localhost`)
      - traefik.http.services.sonarr.loadbalancer.server.port=7000
      - traefik.http.routers.sonarr.tls=true
      #- traefik.http.routers.emby.entrypoints=entryhttps
      #- traefik.http.routers.sonarr.certresolver=certresolver # em traefik.yml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_paulo
    volumes:
      - /home/butt/Docker/sonarr/data:/config
      - /media/butt/backup/Videos/MovieFlix/tvseries:/tv #optional
      - /home/butt/Downloads/qBittorrent:/downloads #o mesmo do qBittorrent
    ports:
      - 7000:7000
    restart: unless-stopped
#services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    labels:
      - traefik.http.routers.radarr.rule=Host(`radarr.localhost`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.tls=true
      #- traefik.http.routers.emby.entrypoints=entryhttps
      #- traefik.http.routers.emby.certresolver=certresolver# em traefik.yml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_paulo
    volumes:
      - /home/butt/Docker/radarr/data:/config
      - /media/butt/backup/Videos/MovieFlix/movies:/movies #optional
      - /home/butt/Downloads/qBittorrent:/downloads #o mesmo do qBittorrent
    ports:
      - 7878:7878
    restart: unless-stopped
#services: 
  emby:
    image: emby/embyserver:latest
    container_name: buttflix
    labels:
      - traefik.http.routers.emby.rule=Host(`buttflix.localhost`)
      - traefik.http.services.emby.loadbalancer.server.port=8096
      - traefik.http.routers.emby.tls=true
      #- traefik.http.routers.emby.entrypoints=entryhttps
      #- traefik.http.routers.emby.certresolver=staging # em traefik.yml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_paulo
    volumes:
      #- /home/butt/Docker/emby/system:/system
      - /home/butt/Docker/emby/config:/config
      - /media/butt/backup/Videos:/mnt/share1
      - /media/butt/ext4NTFS:/mnt/share2
    ports:
      - 5000:8096
      #- 8001:8920
    restart: unless-stopped
 
   
    
