version: "2.1"
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns	
    container_name: duckdns	
    environment:	
    - PUID=1000	
    - PGID=100	
    - TZ=America/Sao_Paulo	
    - SUBDOMAINS=userverhome-c001
    - TOKEN=a24ba2c9-aa4d-4c00-b4de-db3baa414f94 # fabriciogmabillot@gmail.com
    #- TOKEN=ad68a933-0ece-445c-ae15-aecfb96c9c5c # fabricio.butt@gmail.com
    - LOG_FILE=false
    volumes:
      - /home/butt/Docker/duckdns/config:/app
    restart: unless-stopped	 
#
    networks:
      - frontend